### ISSUE TITLE
self.reset() NotImplementedError

### ISSUE THREAD

**Issue by radsimu** [hackthemarket/gym-trading#8]
After I installed the gym and it got registered, all I did was to run the following:

```
import gym
import gym_trading
import numpy as np
import pandas as pd
import matplotlib as mpl
import matplotlib.pyplot as plt
import quandl
from matplotlib import interactive

interactive(True)
quandl.ApiConfig.api_key = 'my quandl api key here'
env = gym.make('trading-v0')
```

And got

```
WARN: gym.spaces.Box autodetected dtype as <type 'numpy.float32'>. Please provide explicit dtype.
Traceback (most recent call last):
  File "trading.py", line 12, in <module>
    env = gym.make('trading-v0')
  File "/usr/local/lib/python2.7/site-packages/gym/envs/registration.py", line 167, in make
    return registry.make(id)
  File "/usr/local/lib/python2.7/site-packages/gym/envs/registration.py", line 119, in make
    env = spec.make()
  File "/usr/local/lib/python2.7/site-packages/gym/envs/registration.py", line 86, in make
    env = cls(**self._kwargs)
  File "/Users/simradu/reinforcement-learning-an-introduction/my_gyms/gym-trading/gym_trading/envs/trading_env.py", line 193, in __init__
    self.reset()
  File "/usr/local/lib/python2.7/site-packages/gym/core.py", line 71, in reset
    raise NotImplementedError
```

**Comment by marleymwangi** [comment]
Hey, got the same error. Did you manage to resolve the issue?

**Comment by zackgow** [comment]
For anyone else who is receiving this error, check out this pull request: https://github.com/hackthemarket/gym-trading/pull/6/commits/7d51f8cd6319783f1950e1637c0563968a7b8e7d

@pimlinders thanks!

**Comment by FanScy** [comment]
Hey, you can just downgrade the version of gym. It is the cause of old version.
